# Generated by Django 5.2.7 on 2025-10-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_unit_type'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovementitem',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='stockmovementitem',
            name='product',
        ),
        migrations.CreateModel(
            name='StokHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_turu', models.CharField(choices=[('IN', 'Stok Girişi'), ('OUT', 'Stok Çıkışı')], max_length=3, verbose_name='Hareket Türü')),
                ('referans_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referans No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='StokHareketKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Maliyet')),
                ('hareket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stock.stokhareket', verbose_name='Hareket')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Hareket Kalemi',
                'verbose_name_plural': 'Stok Hareket Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='StokLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('hareket_turu', models.CharField(choices=[('IN', 'Stok Girişi'), ('OUT', 'Stok Çıkışı')], max_length=3, verbose_name='Hareket Türü')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('hareket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stokhareket', verbose_name='Hareket')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_loglari', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Log',
                'verbose_name_plural': 'Stok Logları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='StockLog',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='StockMovementItem',
        ),
    ]
