# Generated by Django 5.2.7 on 2025-10-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockmovement_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stokhareketkalemi',
            name='birim_maliyet',
        ),
    ]
