# Generated by Django 5.2.7 on 2025-10-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barcode')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stock Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('initial_quantity', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity')),
                ('unit_type', models.CharField(choices=[('PCS', 'Piece'), ('BOX', 'Box'), ('PKG', 'Package'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Ton'), ('L', 'Liter'), ('ML', 'Milliliter')], default='PCS', max_length=10, verbose_name='Unit Type')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Cost')),
                ('critical_stock_level', models.PositiveIntegerField(default=0, verbose_name='Critical Stock Level')),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Warehouse Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
