# Generated by Django 5.2.7 on 2025-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PCS', 'Piece'), ('BOX', 'Box'), ('PKG', 'Package'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Ton'), ('L', 'Liter'), ('ML', 'Milliliter'), ('SET', 'Set'), ('PALLET', 'Pallet')], default='PCS', max_length=10, verbose_name='Unit Type'),
        ),
    ]
